macro_rules! declare_bones {
    ($name:ident, $type:ty) => {
        pub(crate) static $name: [[usize; 4]; 5] = [
            [
                <$type>::Head as usize,
                <$type>::Neck as usize,
                <$type>::Spine4 as usize,
                <$type>::Pelvis as usize,
            ],
            [
                <$type>::Neck as usize,
                <$type>::L_Shoulder_Twst1 as usize,
                <$type>::L_Elbow_Ndl as usize,
                <$type>::L_Hand as usize,
            ],
            [
                <$type>::Neck as usize,
                <$type>::R_Shoulder_Twst1 as usize,
                <$type>::R_Elbow_Ndl as usize,
                <$type>::R_Hand as usize,
            ],
            [
                <$type>::Pelvis as usize,
                <$type>::L_Hip as usize,
                <$type>::L_Knee_Ndl as usize,
                <$type>::L_Foot as usize,
            ],
            [
                <$type>::Pelvis as usize,
                <$type>::R_Hip as usize,
                <$type>::R_Knee_Ndl as usize,
                <$type>::R_Foot as usize,
            ],
        ];
    };
}

declare_bones!(MALE_BONES, MaleBones);
declare_bones!(FEMALE_BONES, FemaleBones);
declare_bones!(BOT_BONES, BotBones);

#[repr(usize)]
#[allow(non_camel_case_types, dead_code)]
pub enum CommonBones {
    Root = 1,
    Head = 8,
}

#[repr(usize)]
#[allow(non_camel_case_types, dead_code)]
pub enum MaleBones {
    Skeleton = 0,
    Root = 1,
    Splitter = 2,
    Spine1 = 3,
    Spine2 = 4,
    Spine3 = 5,
    Spine4 = 6,
    Neck = 7,
    Head = 8,
    Mouth_Top = 9,
    L_Brows = 10,
    R_Eyeball = 11,
    Jaw = 12,
    Mouth_Bot = 13,
    L_Eyeball = 14,
    L_EyeLids = 15,
    MouthCorner = 16,
    R_EyeLids = 17,
    R_Brows = 18,
    R_Lower_EyeLid = 19,
    L_Lower_EyeLid = 20,
    Collar = 21,
    L_Clavicle = 22,
    L_Shoulder = 23,
    L_Elbow = 24,
    L_Hand = 25,
    L_WeaponPoint = 26,
    L_Thumb1 = 27,
    L_Thumb2 = 28,
    L_Thumb3 = 29,
    L_Index1 = 30,
    L_Index2 = 31,
    L_Index3 = 32,
    L_Middle1 = 33,
    L_Middle2 = 34,
    L_Middle3 = 35,
    L_Pinky1 = 36,
    L_Pinky2 = 37,
    L_Pinky3 = 38,
    L_Ring1 = 39,
    L_Ring2 = 40,
    L_Ring3 = 41,
    L_Elbow_Ndl = 42,
    L_Elbow_Twst2 = 43,
    L_Elbow_Twst3 = 44,
    L_Shoulder_Twst1 = 45,
    L_Shoulder_Helper = 46,
    L_Shoulder_Twst3 = 47,
    R_Clavicle = 48,
    R_Shoulder = 49,
    R_Elbow = 50,
    R_Hand = 51,
    R_WeaponPoint = 52,
    R_Thumb1 = 53,
    R_Thumb2 = 54,
    R_Thumb3 = 55,
    R_Index1 = 56,
    R_Index2 = 57,
    R_Index3 = 58,
    R_Middle1 = 59,
    R_Middle2 = 60,
    R_Middle3 = 61,
    R_Pinky1 = 62,
    R_Pinky2 = 63,
    R_Pinky3 = 64,
    R_Ring1 = 65,
    R_Ring2 = 66,
    R_Ring3 = 67,
    R_Elbow_Ndl = 68,
    R_Elbow_Twst2 = 69,
    R_Elbow_Twst3 = 70,
    R_Shoulder_Twst1 = 71,
    R_Shoulder_Helper = 72,
    R_Shoulder_Twst3 = 73,
    Pelvis = 74,
    R_Foot_IKpv_IUE = 75,
    L_Foot_IKpv_IUE = 76,
    L_Hip = 77,
    L_Knee = 78,
    L_Knee_Ndl = 79,
    L_Foot = 80,
    L_Toe = 81,
    L_Hip_Twst1 = 82,
    L_Hip_Twst3 = 83,
    R_Hip = 84,
    R_Knee = 85,
    R_Knee_Ndl = 86,
    R_Foot = 87,
    R_Toe = 88,
    R_Hip_Twst1 = 89,
    R_Hip_Twst3 = 90,
    MasterWeaponAim = 91,
    MasterWeapon = 92,
    L_WeaponMaster = 93,
    R_WeaponMaster = 94,
    L_Weapon_HandTarget = 95,
    L_Weapon_HandOffset = 96,
    R_Weapon_HandTarget = 97,
    L_Hand_IKpv_IUE = 98,
    R_Hand_IKpv_IUE = 99,
    IK_RootTarget = 100,
    L_IK_FootTarget = 101,
    R_IK_FootTarget = 102,
    TP_Camera = 103,
}

#[repr(usize)]
#[allow(non_camel_case_types, dead_code)]
pub enum FemaleBones {
    Skeleton = 0,
    Root = 1,
    Splitter = 2,
    Spine1 = 3,
    Spine2 = 4,
    Spine3 = 5,
    Spine4 = 6,
    Neck = 7,
    Head = 8,
    Jaw = 9,
    Mouth_Bot = 10,
    R_Eyeball = 11,
    Mouth_Top = 12,
    L_Eyeball = 13,
    MouthCorner = 14,
    L_Brows = 15,
    R_Brows = 16,
    R_EyeLids = 17,
    L_EyeLids = 18,
    R_Lower_EyeLid = 19,
    L_Lower_EyeLid = 20,
    Collar = 21,
    L_Clavicle = 22,
    L_Shoulder = 23,
    L_Elbow = 24,
    L_Hand = 25,
    L_Pinky1 = 26,
    L_Pinky2 = 27,
    L_Pinky3 = 28,
    L_Thumb1 = 29,
    L_Thumb2 = 30,
    L_Thumb3 = 31,
    L_Index1 = 32,
    L_Index2 = 33,
    L_Index3 = 34,
    L_Ring1 = 35,
    L_Ring2 = 36,
    L_Ring3 = 37,
    L_Middle1 = 38,
    L_Middle2 = 39,
    L_Middle3 = 40,
    L_WeaponPoint = 41,
    L_Elbow_Ndl = 42,
    L_Elbow_Twst2 = 43,
    L_Elbow_Twst3 = 44,
    L_Shoulder_Twst1 = 45,
    L_Shoulder_Twst3 = 46,
    R_Clavicle = 47,
    R_Shoulder = 48,
    R_Elbow = 49,
    R_Hand = 50,
    R_WeaponPoint = 51,
    R_Index1 = 52,
    R_Index2 = 53,
    R_Index3 = 54,
    R_Thumb1 = 55,
    R_Thumb2 = 56,
    R_Thumb3 = 57,
    R_Ring1 = 58,
    R_Ring2 = 59,
    R_Ring3 = 60,
    R_Pinky1 = 61,
    R_Pinky2 = 62,
    R_Pinky3 = 63,
    R_Middle1 = 64,
    R_Middle2 = 65,
    R_Middle3 = 66,
    R_Elbow_Ndl = 67,
    R_Elbow_Twst2 = 68,
    R_Elbow_Twst3 = 69,
    R_Shoulder_Twst1 = 70,
    R_Shoulder_Twst3 = 71,
    Pelvis = 72,
    R_Foot_IKpv_IUE = 73,
    L_Foot_IKpv_IUE = 74,
    L_Hip = 75,
    L_Knee = 76,
    L_Knee_Ndl = 77,
    L_Foot = 78,
    L_Toe = 79,
    L_Hip_Twst1 = 80,
    L_Hip_Twst3 = 81,
    R_Hip = 82,
    R_Knee = 83,
    R_Knee_Ndl = 84,
    R_Foot = 85,
    R_Toe = 86,
    R_Hip_Twst1 = 87,
    R_Hip_Twst3 = 88,
    MasterWeaponAim = 89,
    MasterWeapon = 90,
    L_WeaponMaster = 91,
    R_WeaponMaster = 92,
    R_Weapon_HandTarget = 93,
    L_Weapon_HandTarget = 94,
    L_Weapon_HandOffset = 95,
    L_Hand_IKpv_IUE = 96,
    R_Hand_IKpv_IUE = 97,
    IK_RootTarget = 98,
    L_IK_FootTarget = 99,
    R_IK_FootTarget = 100,
}

#[repr(usize)]
#[allow(non_camel_case_types, dead_code)]
pub enum BotBones {
    Skeleton = 0,
    Root = 1,
    Splitter = 2,
    Spine1 = 3,
    Spine2 = 4,
    Spine3 = 5,
    Spine4 = 6,
    Neck = 7,
    Head = 8,
    Collar = 9,
    L_Clavicle = 10,
    L_Shoulder = 11,
    L_Elbow = 12,
    L_Hand = 13,
    L_Thumb1 = 14,
    L_Thumb2 = 15,
    L_Thumb3 = 16,
    L_WeaponPoint = 17,
    L_Index1 = 18,
    L_Index2 = 19,
    L_Index3 = 20,
    L_Middle1 = 21,
    L_Middle2 = 22,
    L_Middle3 = 23,
    L_Pinky1 = 24,
    L_Pinky2 = 25,
    L_Pinky3 = 26,
    L_Ring1 = 27,
    L_Ring2 = 28,
    L_Ring3 = 29,
    L_Elbow_Ndl = 30,
    L_Elbow_Twst2 = 31,
    L_Elbow_Twst3 = 32,
    L_Shoulder_Twst1 = 33,
    L_Shoulder_Twst3 = 34,
    R_Clavicle = 35,
    R_Shoulder = 36,
    R_Elbow = 37,
    R_Hand = 38,
    R_Thumb1 = 39,
    R_Thumb2 = 40,
    R_Thumb3 = 41,
    R_WeaponPoint = 42,
    R_Index1 = 43,
    R_Index2 = 44,
    R_Index3 = 45,
    R_Middle1 = 46,
    R_Middle2 = 47,
    R_Middle3 = 48,
    R_Pinky1 = 49,
    R_Pinky2 = 50,
    R_Pinky3 = 51,
    R_Ring1 = 52,
    R_Ring2 = 53,
    R_Ring3 = 54,
    R_Elbow_Ndl = 55,
    R_Elbow_Twst2 = 56,
    R_Elbow_Twst3 = 57,
    R_Shoulder_Twst1 = 58,
    R_Shoulder_Twst3 = 59,
    Pelvis = 60,
    R_Foot_IKpv_IUE = 61,
    L_Foot_IKpv_IUE = 62,
    L_Hip = 63,
    L_Knee = 64,
    L_Knee_Ndl = 65,
    L_Foot = 66,
    L_Toe = 67,
    L_Toe_end = 68,
    L_Foot_end = 69,
    L_ToeRoll_end = 70,
    L_OuterRoll_end = 71,
    L_HeelRoll_end = 72,
    L_InnerRoll_end = 73,
    L_SwivelRoll_end = 74,
    L_Hip_Twst1 = 75,
    L_Hip_Twst3 = 76,
    R_Hip = 77,
    R_Knee = 78,
    R_Knee_Ndl = 79,
    R_Foot = 80,
    R_Toe = 81,
    R_Toe_end = 82,
    R_Foot_end = 83,
    R_ToeRoll_end = 84,
    R_OuterRoll_end = 85,
    R_HeelRoll_end = 86,
    R_InnerRoll_end = 87,
    R_SwivelRoll_end = 88,
    R_Hip_Twst1 = 89,
    R_Hip_Twst3 = 90,
    MasterWeaponAim = 91,
    MasterWeapon = 92,
    L_WeaponMaster = 93,
    R_WeaponMaster = 94,
    L_Weapon_HandTarget = 95,
    L_Weapon_HandOffset = 96,
    R_Weapon_HandTarget = 97,
    L_Hand_IKpv_IUE = 98,
    R_Hand_IKpv_IUE = 99,
    IK_RootTarget = 100,
    L_IK_FootTarget = 101,
    R_IK_FootTarget = 102,
}
